<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="lahiruh1" failures="1" tests="1" name="NegativeLogInTest-CH" time="0.093" errors="0" timestamp="2023-10-31T16:11:56 AST">
  <testcase classname="com.alaqahtml5.qa.loginpagetests.LoginTestAll" name="logInTestAll" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: File src\test\resources\dataproviders\LoginTestAll\logInTestAll.csv was not found.
[Ljava.lang.StackTraceElement;@6a9140a3">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: File src\test\resources\dataproviders\LoginTestAll\logInTestAll.csv was not found.
[Ljava.lang.StackTraceElement;@6a9140a3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: File src\test\resources\dataproviders\LoginTestAll\logInTestAll.csv was not found.
[Ljava.lang.StackTraceElement;@6a9140a3
at com.alaqahtml5.qa.base.CsvDataProviders.csvReader(CsvDataProviders.java:45)
... 19 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- logInTestAll -->
</testsuite> <!-- NegativeLogInTest-CH -->
